### ISSUE TITLE
Need hotkey or other alternative to a wakeword

### ISSUE THREAD

**Issue by modgeosys** [voqal/voqal#59]
Picovoice doesn't like me anymore for some reason, maybe because I need two separate accounts for personal and work.  The docs mention a hotkey as an alternative to a wake word, but I can't find it.

**Comment by modgeosys** [comment]
9:33 AM [INFO] Voqal initialized. Version: 2024.3.0
9:33 AM [INFO] Bridge service initialized for project: nav-algorithms
9:33 AM [INFO] Starting speech service
9:33 AM [INFO] Extracted natives to: /tmp/voqal-natives - Project: nav-algorithms
9:33 AM [INFO] Cobra version: 2.0.0
9:33 AM [INFO] Intent detector disabled
9:33 AM [INFO] Listening for wake word...
9:33 AM [INFO] Sending telemetry data to Voqal
9:33 AM [INFO] Wake word detected
9:33 AM [INFO] Status changed from ENABLED to LISTENING
9:33 AM [INFO] Playing resource: notification/listening
9:33 AM [INFO] Developer talking: true
9:33 AM [INFO] Developer talking: false
9:33 AM [INFO] Status changed from LISTENING to TRANSCRIBING
9:33 AM [INFO] Leopard version: 2.0.0
9:33 AM [WARNING] Error message 0: Picovoice Error (code `00000136`)
9:33 AM [WARNING] Error message 1: Picovoice Error (code `00000136`)
9:33 AM [WARNING] Error message 2: Picovoice Error (code `0000012C`)
9:33 AM [SEVERE] Failed to initialize Leopard: ACTIVATION_REFUSED

**Comment by modgeosys** [comment]
I also have a powerful GPU on one of my workstations.  Maybe a local model for some ops would be possible.

**Comment by BFergerson** [comment]
I haven't been liking Picovoice lately. The product or the custom service. Version 2024.4.0 will allow you to completely replace Picovoice with Deepgram. The only caveat is that it'll cost $0.30 an hour to use Deepgram, but they give you $200 in free credit, and I'd imagine that price will go down with time.

Picovoice is very aggressive when it comes to multiple accounts. Their limitations are what's currently holding back version 2024.4.0. I'd create another account to release 2024.4.0, but I've already gotten a warning, so I'm sure they'd ban me if I tried making a new account.

As for hotkeys, do you mean the push-to-talk functionality? If so, you can customize that here:
![image](https://github.com/voqal/voqal/assets/3278877/7f8b8721-da78-4b8b-bc73-782ee5cac892)

**Comment by BFergerson** [comment]
I should note there is a bug in the push-to-talk functionality where if you hold it down, it'll cause multiple transcriptions. That's fixed in version 2024.4.0.

**Comment by modgeosys** [comment]
Push-to-talk sounds good to me!  I'll try that next.

**Comment by BFergerson** [comment]
Closing. Updated documentation to include keymap settings (https://docs.voqal.dev/configuration/wake_detection).
