### ISSUE TITLE
Hook into JetBrains refactoring

### ISSUE THREAD

**Issue by modgeosys** [voqal/voqal#72]
I just had Voqal rename a class, and although it successfully did so for the class definition itself, it didn't update references from the rest of the project.  It would be nice if I could tell Voqal to use the refactoring feature of the IDE.  In this case, it would use the Rename refactoring tool to do the honors.

**Comment by BFergerson** [comment]
Fix is in EAP version 2024.6.1712108706. It should propagate name changes much better now.

**Comment by BFergerson** [comment]
More complete fix in 2024.6.1712119196
